#!/bin/bash
set -e

########################################################################
# Author: Elias Bourgess					       #
# Email: elias@ebourgess.com					       #	
# Website: https://ebourgess.com				       #
########################################################################


echo "##########################################"
echo "	 	Installing Utilities	 	"
echo "##########################################"

echo ""

echo "##########################################"
echo "		Installing Audio		"
echo "##########################################"

sudo pacman -S --noconfirm --needed pulseaudio pulseaudio-alsa pavucontrol
sudo pacman -S --noconfirm --needed alsa-utils alsa-plugins alsa-lib alsa-firmware
sudo pacman -S --noconfirm --needed gstreamer gst-plugins-good gst-plugins-bad gst-plugins-base gst-plugins-ugly
sudo pacman -S --noconfirm --needed volumeicon playerctl


echo "###########################################"
echo "		Audio software installed	 "
echo "###########################################"

echo ""

echo "###########################################"
echo "		Installing Bluetooth		 "
echo "###########################################"

sudo pacman -S --noconfirm --needed pulseaudio-bluetooth blueberry
sudo pacman -S --noconfirm --needed bluez bluez-utils blues-libs bluez-firmware

sudo systemctl enable bluetooth.service
sudo systemctl start bluetooth.service

sudo sed -i 's/'#AutoEnable=false'/'AutoEnable=true'/g' /etc/bluetooth/main.conf

echo "###########################################"
echo "		Bluetooth installed		 "
echo "###########################################"

echo ""

echo "###########################################"
echo "		Utilities Installed		 "
echo "###########################################"
